Podpora za Biblatex (in biber)
ul-fmf/fmfdelo pull request #38
Opened 2024-01-29 17:38 UTC by lunar-starlight

Definirala sem UL/FMF stil citiranja z `biblatex` ukazi.
To poenostavi reševanje #35, poleg tega pa lahko sedaj odstranimo `bibentry`, ki je nehal delati.

Closes #36

2024-01-30 09:01 UTC, matijapretnar requested changes
Videti mi je veliko bolj vzdržno, tudi biber mi je delal iz prve, je pa za začetek treba popraviti še par detajlov.

2024-01-30 09:30 UTC, lunar-starlight commented on predloge/magisterij-primer-sl/literatura.bib
> Tole sem opazil pri primerjavi pdfjev:
> 
> `diploma-primer`:
> 
>   * Za tam, kjer so urlji, je izginilo "dostopno na"
>   * Za spletne strani je izginilo "[ogled: ...]"
>
Spletni viri morajo zdaj biti navedeni kot `@online`, ne `@misc`
> 
>   * Pred imenom revije zdaj piše "v: "
>   * Pred številkami strani zdaj piše "str. "
> 
To je zato, ker to zgleda zahtevajo pogoji na spletni učilnici. V `bibtex`u je en vir (`@inproceedings`) kjer se to dvoje vseeno izpisuje, medtem ko spletna učilnica pa pravi, da naj se izpisuje vedno, tako da ne vem točno kako to rešiti.
> 
> 
> `magisterij-sl`:
> 
>   * osnovna literatura je normalno oštevilčena, ne z referencami / mogoče je to celo v redu
>
Meni se zdi smiselno, glede na to da mora biti urejena po pomembnosti. Mogoče bi bilo smiselno dodati še citat, da bralec ve, kateri sklici so na ključno literaturo.
> 
>   * zanimivo tu so urlji in datumi ogledov
>
Za magistrska dela je .bib pravilen, tako da pravilno izpiše tudi podatke o dostopu.
> 
>   * urlji so malo drugače oblikovani in lomljeni
>
To je razlika v razmakih med vrsticami ipd. Lahko poskusim spremeniti, ampak se po moje ne splača.
> 
>   * [5] - DOI je drugače oblikovan
>
DOI polje je sedaj povezava na doi.org, zato je oblikovan kot povezava. Meni se zdi pravilno (da ne podvajamo še z "dostopno na doi.org"). Tudi v člankih se mi zdi da je to standardno.
> 
> 
> `magisterij-en`:
> 
>   * [5] "in: "
>
Enako kot zgoraj `v:`
> 
>   * [9] drugačno besedilo in datum za visited/viewed, ampak je videti, da je bilo že prej nekonsistentno
>
`visited on` je kar `biblatex` naredi sam po sebi, lahko spremenim na `viewed`, če je kakšna preferenca.

2024-01-30 09:36 UTC, matijapretnar commented on predloge/magisterij-primer-sl/literatura.bib
@online/@misc: Ok, je treba popraviti v primerih diplome.
v/str: mogoče bi to vprašali Majo Klavžar
sklici na ključno literaturo: meni je oboje v redu, samo ne bi imel dvojnih številk: ali je sklic na začetku in je videti grdo, ali pa na koncu in se ga ne opazi
oblikovanje: v redu je, kakor je
doi: se strinjam
visited: ja, pustimo potem default

2024-01-30 09:59 UTC, lunar-starlight commented on bibstyle/stil.dbj
> -  vonx,%: Sort without von part
Našla sem [tole](https://tex.stackexchange.com/questions/136005/sorting-and-citing-names-with-von-prefix-using-biblatex), če kdaj hočemo kaj rešiti.
`biblatex` že sam po sebi ignorira `van` in podobno, tako da bi bilo za pogledati, kaj se dogaja.
Obstaja polje `sortname`, ki naj bi se načeloma uporabljalo za to (skupaj z `useprefix=true`).

2024-01-30 20:09 UTC, lunar-starlight commented on predloge/magisterij-primer-sl/literatura.bib
Glede ključne literature: jaz ne vidim preprostega načina, kako oštevilčiti literaturo z njihovimi citati v glavni literaturi, tako da bi pustila kot je.

2024-02-26 11:14 UTC, matijapretnar commented
Ja, zdaj je veliko bolje. Našel sem še:

- pri `@article{vec-avtorjev}` se v PDF-ju pokaže odvečen niz `en`
- pri `@book{kalisnik}` je povezava izginila

2024-02-29 11:56 UTC, matijapretnar approved these changes

2024-02-29 11:56 UTC, merged